---
all:
    vars:
      ansible_user: azureuser
      ansible_ssh_private_key_file: ./sshkey
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    children:
      jenkins:
        hosts:
          "www.personalverwaltungssystem.com":
            ansible_host: 20.107.39.99
      webserver:
        hosts:
          "techstarter3.ddns.net":
            ansible_host: 20.107.39.83